name: toolchain
on:
  push:
    branches: '*'
    tags: "[0-9]+.[0-9]+.[0-9]+"
  schedule:
    - cron:  '0 8,22 * * *'
  workflow_dispatch:
  pull_request:

permissions:
  contents: write

jobs:
  build-swift-toolchain:
    strategy:
      matrix:
        swift_branch: ['release/5.10', 'release/6.0', 'main']

    runs-on: macos-14

    steps:
    - name: Clone scripts
      uses: actions/checkout@v4
    - name: Install Build Tools
      run: brew install cmake ninja autoconf automake libtool pkg-config git-lfs
    - name: Setup Android Tools
      id: setup-ndk
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r26d
    - name: Check NDK
      run: ls ${ANDROID_NDK_HOME}
      env:
        ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
    - name: Clone Swift
      run: scripts/001-fetch-swift.sh
      env:
        SWIFT_BRANCH: ${{ matrix.swift_branch }}
    - name: Build Toolchain
      run: scripts/010-build-toolchain.sh
      env:
        SWIFT_BRANCH: ${{ matrix.swift_branch }}
        ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

